### ISSUE TITLE
Modules in File Folder are not found

### ISSUE THREAD

**Issue by yannerous** [GSG-Robots/comPYner#1]
Modules that are saved in the same folder as the input file are not found while combining the files.

Is this expected behavior? If yes, what is the reason for not checking those files?

![image](https://github.com/user-attachments/assets/84ae7708-fffb-4c2e-96ff-639c46666f60)

Full error message:
PS D:\OneDrive\Yannick\Programmieren\Python\CompynerTest> compyner mainFile.py -o out.py                                      
Globals in __main__:
  Import1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Scripts\compyner.exe\__main__.py", line 7, in <module>
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\compyner\__main__.py", line 22, in main      
    compyner.add_module("__main__", module_ast)
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\compyner\engine.py", line 514, in add_module 
    tree = GlobalReplacer(self, gf.globals, parent=parent).visit(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\compyner\engine.py", line 230, in visit_Import
    replace_import = self.compyner.load_module(alias.name, self.parent)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\compyner\engine.py", line 475, in load_module
    return self._load_module(spec, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\compyner\engine.py", line 479, in _load_module
    raise ModuleNotFoundError(f"Module {name} not found")
ModuleNotFoundError: Module Import1 not found

**Comment by J0J0HA** [comment]
Sorry I did not respond, I did not get a notification and found it by "accident" just now.

This is not supposed to be that way! The public version of this tool is outdated and has some bugs which are fixed in our copy. I will update the public version soon (this is why I noticed your issue in the first place) and if you then (will notify you) are still interested, I would like you to try the new version and see if this still happens, so I can go ahead to fix this issue.

Note that this tool is only actively tested for our Robot Game (MicroPython, SpikePrime V2/Legacy) code, although it certainly should be able to handle other codebases too.

**Comment by J0J0HA** [comment]
Hi @yannerous !
I have updated this repository and cleaned up the code, removing unused and outdated stuff. I found the reason for your issue and fixed it, so this should work now.

The problem was the working directory not being on path, so it could have been workaround-ed by using:
```batch
set PYTHONPATH=%PYTHONPATH%;%cd%
compyner mainFile.py -o out.py
```

compyner now does this automatically when called using th cli.
